name: Pipeline Diaria GoldWatch

# Define quando a automação será executada
on:
  schedule:
    - cron: '0 12 * * *' # Executa todo dia às 12:00 UTC (09:00 no Brasil)
  workflow_dispatch: # Permite que você clique em um botão e rode manualmente

jobs:
  executar_etl:
    runs-on: ubuntu-latest # Usa um servidor Linux do GitHub

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v3

      - name: Configurar o Python no servidor
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar bibliotecas necessarias
        run: pip install -r requirements.txt

      - name: Rodar a Pipeline de Dados
        run: python pipeline.py

      - name: Salvar o Banco de Dados atualizado no GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add commodities.db
          git commit -m "Auto-update: Dados coletados em $(date)" || echo "Sem mudanças"
          git push